### ISSUE TITLE
Shop data is appended, not refreshed, causing duplicates

### ISSUE THREAD

**Issue by MWDelaney** [dleatherman/eleventy-plugin-shopify#10]
**Describe the bug**
This plugin, during `npm run dev`, with my shop data, re-runs its query after each save of a watched file and appends the results to the existing data, doubling the number of Products, Pages, Collections, etc. each time.

**Expected behavior**
Data should be polled once from Shopify when Eleventy is first started.

**Console output showing details**
```
SHOPIFY:GETTING SHOP INFO
SHOPIFY:GETTING PRODUCTS
SHOPIFY:GETTING COLLECTIONS
SHOPIFY:GETTING PAGES
SHOPIFY:GETTING ARTICLES
SHOPIFY:SUCCESSFULLY RETRIEVED <shop name>
SHOPIFY:SUCCESSFULLY RETRIEVED 1 PRODUCT
SHOPIFY:SUCCESSFULLY RETRIEVED 9 COLLECTIONS
SHOPIFY:SUCCESSFULLY RETRIEVED 1 PAGE
SHOPIFY:SUCCESSFULLY RETRIEVED 0 ARTICLES
SHOPIFY:MAPPING PRODUCTS TO COLLECTIONS
SHOPIFY:SUCCESSFULLY MAPPED PRODUCTS TO COLLECTIONS
[11ty] Wrote 20 files in 8.93 seconds (446.5ms each, v2.0.0-canary.15)
[11ty] Watching…
[11ty] Server at http://10.0.2.113:8080/ or http://169.254.65.1:8080/ or http://169.254.51.66:8080/ or http://localhost:8080/
[11ty] File changed: src/assets/styles/_bootstrap.scss
SHOPIFY:GETTING SHOP INFO
SHOPIFY:GETTING PRODUCTS
SHOPIFY:GETTING COLLECTIONS
SHOPIFY:GETTING PAGES
SHOPIFY:GETTING ARTICLES
SHOPIFY:SUCCESSFULLY RETRIEVED <shop name>
SHOPIFY:SUCCESSFULLY RETRIEVED 2 PRODUCTS
SHOPIFY:SUCCESSFULLY RETRIEVED 18 COLLECTIONS
SHOPIFY:SUCCESSFULLY RETRIEVED 2 PAGES
SHOPIFY:SUCCESSFULLY RETRIEVED 0 ARTICLES
SHOPIFY:MAPPING PRODUCTS TO COLLECTIONS
SHOPIFY:SUCCESSFULLY MAPPED PRODUCTS TO COLLECTIONS
[11ty] Wrote 20 files in 2.97 seconds (148.5ms each, v2.0.0-canary.15)
```

**Additional context**
I'm using a newer version of Eleventy than is directly supported by this plugin, which could be the issue?

**Comment by ed-ponce** [comment]
I’m having this exact problem.

**Comment by dleatherman** [comment]
@patrulea can you let me know what version of `@11ty/eleventy` you're using? I think this should be resolved with `^1.0.2`

**Comment by ed-ponce** [comment]
I was on `1.0.2` and now tried with `2.0.0-canary.16` and the problem persists. Every time I save a file while serving, the rebuild triggers and duplicate data appends to the old one, duplicating it.

**Comment by ItsEthanH** [comment]
Any updates on this? I'm on eleventy 2.0 and am having the same issue :(

**Comment by ed-ponce** [comment]
> Any updates on this? I'm on eleventy 2.0 and am having the same issue :(

I ended up just pulling the data via GraphQL by hand.

**Comment by ItsEthanH** [comment]
Looks as if Dan's looking over this. In the meantime, I ended up using a de-duplication filter:

In _11ty/filters/getUniqueProducts.js...
```
function getUniqueProducts(array) {
  const uniqueObjects = {};
  return array.filter((obj) => !uniqueObjects[obj.id] && (uniqueObjects[obj.id] = true));
}
```

In eleventy.config.js...

```
const getUniqueProducts = require('./src/_11ty/filters/getUniqueProducts').getUniqueProducts;

module.exports = function (eleventyConfig) {
  eleventyConfig.addFilter('getUniqueProducts', getUniqueProducts);
  ...
}
```

Can then just call {{ shopify.products | getUniqueProducts }} as needed

**Comment by dleatherman** [comment]
Closed thanks to @ItsEthanH!

**Comment by ItsEthanH** [comment]
My first open source contribution :D 

Thanks @dleatherman!
